apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.version }}
  labels:
    {{- include "default.labelsAppVersion" . | indent 2 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "default.labelsAppVersion" . | indent 2 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 30%    
  template:
    metadata:
      labels:
        {{- include "default.labelsAppVersion" . | indent 4 }}
    spec:
      shareProcessNamespace: true
      containers:
      - name: {{ .Values.deployment.image.name }}  
        image: {{ .Values.image }}  
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        env:
      {{- range .Values.deployment.container.env }}          
        - name: {{.name }}
          value: {{ .value }}
      {{- end }}
        - name: version
          value: "{{ tpl .Values.templateVersion .}}"
        - name: IP_DOCKER_HOST
          value: {{ .Values.ipDockerHost }}  
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName   
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        #{{- with .Values.deployment.health }}
        #readinessProbe:
        #  httpGet:
        #    path: {{ .path }}
        #    port: {{ .port }}
        #  initialDelaySeconds: {{ .readinessInitialDelaySeconds }}
        #  periodSeconds: {{ .readinessPeriodSeconds }}
        #livenessProbe:
        #  httpGet:
        #    path: {{ .path }}
        #    port: {{ .port }}
        #  initialDelaySeconds: {{ .livenessInitialDelaySeconds }}
        #  periodSeconds: {{ .livenessPeriodSeconds }}
        #startupProbe:
        #  httpGet:
        #    path: {{ .path }}
        #    port: {{ .port }}
        #  failureThreshold: {{ .startUpProbeFailureThreshold }}
        #  periodSeconds: {{ .startUpProbePeriodSeconds }}
        #{{- end }}
        #resources:
        #  requests:
        #    memory: "64Mi"
        #    cpu: "250m"
        #  limits:
        #    memory: "128Mi"
        #    cpu: "500m"


